---
bases:
- ../../environments.yaml

---
helmfiles:
- path: "../../releases/cert-manager/helmfile.yaml"
- path: "../../releases/ingress-nginx/helmfile.yaml"
- path: "../../releases/gitlab-runner/helmfile.yaml"

