apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kube-web-view

namespace: default

resources:
- github.com/hjacobs/kube-web-view/deploy
- ingress.yaml

patchesStrategicMerge:
- deployment.yaml
