bases:
- ../../environments.yaml

---
repositories:
- name: "jetstack"
  url: "https://charts.jetstack.io"

---
releases:
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: "cert-manager"
  version: {{ .Values.helm.cert_manager.version }}
  installed: {{ .Values.helm.cert_manager.enabled | toYaml }}
  set:
  - name: installCRDs
    value: true
